### ISSUE TITLE
Add editorconfig and linter files

### ISSUE THREAD

**Issue by abea** [apostrophecms-legacy/apostrophe-samples#2]
We should add the Apostrophe editor config file as well as .eslintrc and .stylelintrc files in here so that devs using this to test aren't distracted by their editor saying something is an error simply due to style. This is especially important in this that's meant to be used for learning the ropes of Apostrophe.

**Comment by boutell** [comment]
When doing so we need to make sure it passes, of course, but also make sure we add all the dev deps properly.
