### ISSUE TITLE
DB can't connect

### ISSUE THREAD

**Issue by KameronJohnson** [apostrophecms-legacy/apostrophe-samples#6]
Seems to install ok, but getting a DB error when trying to add the admin:

$ node app apostrophe-users:add admin admin

Results in:
```
DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

ERROR: There was an issue connecting to the database. Is it running?
```
& 

```
MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
```

Using node v10.15.3

**Comment by abea** [comment]
Can you run the site without creating a user? I don't think the issue is with this code base. What version of MongoDB are you running? Is it running if you type `mongo` in the terminal?

**Comment by KameronJohnson** [comment]
Ah nevermind, can remove the issue.
